services:
  zomboid-server:
    container_name: zomboid-server
    build:
      context: ./zomboid-server
      dockerfile: Dockerfile
    volumes:
      - ./data:/root/Zomboid
      - ./workshop:/root/.local/share/Steam/steamapps/workshop
    ports:
      - 16261:16261/udp # Port for the server
      - 16261:16261/tcp # TCP port for the server
      - 8766:8766/udp # Steam query port
      - 16262-16272:16262-16272/udp # Direct connection ports
