services:
  zomboid-server:
    container_name: zomboid-server
    build:
      context: ./zomboid-server
      dockerfile: Dockerfile
    volumes:
      - ./data:/root/Zomboid
      - ./workshop:/root/.local/share/Steam/steamapps/workshop
    ports:
      - 16261:16261/udp
      - 16262:16262/udp
      - 27015:27015 # For RCON outside the container
