name: project-zomboid-server

services:
  devcontainer:
    image: project-zomboid-server-devcontainer
    container_name: project-zomboid-server-devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    # Change the init command so that the container doesn't exit
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    volumes:
      # Mount the Docker daemon socket so the devcontainer can run Docker commands
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Mount the project directory as the working directory
      - ${LOCAL_WORKSPACE_FOLDER:-..}:${CONTAINER_WORKSPACE_FOLDER:-/workspaces/project-zomboid-server}
      # Mount a volume for node_modules
      - devcontainer-node_modules:${CONTAINER_WORKSPACE_FOLDER:-/workspaces/project-zomboid-server}/node_modules

volumes:
  devcontainer-node_modules:
    name: project-zomboid-server-devcontainer-node_modules
