exclude = [
  ".git",
  "node_modules",
  "venv",
  ".config",
  ".github",
]

line-length   = 120
indent-width  = 4
target-version = "py312"

[lint]
select       = ["ALL"]
ignore       = [
  "D100",
  "INP001",
  "ERA001",
  "PLW2901",
  "TRY400",
]
fixable      = ["ALL"]

[format]
quote-style               = "double"   # Use double quotes like Black
indent-style              = "space"    # Indent with spaces
skip-magic-trailing-comma = false      # Respect trailing commas
line-ending               = "auto"     # Detect platform line endings
